language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php code-checker/src/code-checker.php
    - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then ./node_modules/.bin/eslint "src/**/*.js"; fi

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - if [ $TRAVIS_PHP_VERSION == "5.3.3" ]; then composer --global config disable-tls true; composer --global config secure-http false; fi
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction
    # Install new Node.js and Eslint
    - >
      if [ $TRAVIS_PHP_VERSION == "7.0" ]; then
      . $HOME/.nvm/nvm.sh;
      nvm install stable;
      nvm use stable;
      npm install;
      npm install eslint;
      fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
